---
name: route-registrar

instance_groups:
- name: route-registrar
  azs: [z1,z2,z3]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: route-registrar
    release: route-registrar
    properties:
      route_registrar:
        external_host: ((route-registrar-external-host))
        external_ip: ((route-registrar-external-ip))
        port: ((route-registrar-port))
        message_bus_servers:
        - host: ((nats-host))
          user: ((nats-username))
          password: ((nats-password))
        health_checker:
          name: ((route-registrar-health-check-name))

variables: []

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: route-registrar
  version: "3"
  url: https://bosh.io/d/github.com/cloudfoundry-community/route-registrar-boshrelease?v=3
  sha1: f6e94922b27a7b0fc2ea81a698af1ee35b46dbf3
