meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: route_registrar
    template: route-registrar
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    properties: {}

networks: (( merge ))

properties:
  route_registrar:
    external_host: (( merge ))
    external_ip: (( merge ))
    port: (( merge ))
    message_bus_servers:
    - host: (( merge ))
      name: nats
      password: nats
    health_checker:
      name: (( merge ))
